Document: floodlight
Title: Debian floodlight Manual
Author: <insert document author here>
Abstract: This manual describes what floodlight is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/floodlight/floodlight.sgml.gz

Format: postscript
Files: /usr/share/doc/floodlight/floodlight.ps.gz

Format: text
Files: /usr/share/doc/floodlight/floodlight.text.gz

Format: HTML
Index: /usr/share/doc/floodlight/html/index.html
Files: /usr/share/doc/floodlight/html/*.html
